// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VanbaApp.Data;

namespace VanbaApp.Migrations
{
    [DbContext(typeof(VanbaContext))]
    partial class VanbaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("VanbaApp.Models.Word", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etymology")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeaningAsAdjective")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeaningAsNoun")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeaningAsVerb")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
